apiVersion: v1
kind: Service
metadata:
  name: mys-service
  namespace: my-sample-app
  labels:
    app: nginx-deployment
spec:
  selector:
    app: nginx-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
